### ISSUE TITLE
Crash when using mixins wrongly...

### ISSUE THREAD

**Issue by bnolan** [less/less.ruby#163]
Shouldn't crash dump.

```
.blah{
color: red;
}

p{
.blah();
}
```
# Error

```
/Library/Ruby/Gems/1.8/gems/less-1.2.21/bin/../lib/less/engine/nodes/element.rb:226:in `to_css': undefined method `call' for .blah (NoMethodError)
.  color: `red`
:Less::Node::Element
    from /Library/Ruby/Gems/1.8/gems/less-1.2.21/bin/../lib/less/engine/nodes/element.rb:107:in `equiv?'
    from /Library/Ruby/Gems/1.8/gems/less-1.2.21/bin/../lib/less/engine/nodes/element.rb:106:in `map'
    from /Library/Ruby/Gems/1.8/gems/less-1.2.21/bin/../lib/less/engine/nodes/element.rb:106:in `equiv?'
    from /Library/Ruby/Gems/1.8/gems/less-1.2.21/bin/../lib/less/engine/nodes/element.rb:61:in `group'
    from /Library/Ruby/Gems/1.8/gems/less-1.2.21/bin/../lib/less/engine/nodes/element.rb:60:in `each'
    from /Library/Ruby/Gems/1.8/gems/less-1.2.21/bin/../lib/less/engine/nodes/element.rb:60:in `group'
    from /Library/Ruby/Gems/1.8/gems/less-1.2.21/bin/../lib/less/engine/nodes/element.rb:56:in `each'
    from /Library/Ruby/Gems/1.8/gems/less-1.2.21/bin/../lib/less/engine/nodes/element.rb:56:in `group'
    from /Library/Ruby/Gems/1.8/gems/less-1.2.21/bin/../lib/less/engine.rb:45:in `to_css'
    from /Library/Ruby/Gems/1.8/gems/less-1.2.21/bin/../lib/less/command.rb:64:in `parse'
    from /Library/Ruby/Gems/1.8/gems/less-1.2.21/bin/../lib/less/command.rb:57:in `run!'
    from /Library/Ruby/Gems/1.8/gems/less-1.2.21/bin/lessc:102
    from /usr/bin/lessc:19:in `load'
    from /usr/bin/lessc:19
```

**Comment by dvilla** [comment]
Hi, bnolan, that bug doesn't crash anymore, I recommend you to update your less gem as well as your ruby version to the latest release to have a better performance in your environment. Have a nice day.
